Vagrant::Config.run do |config|
  config.vm.box = "base"

  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"

  config.vm.network "33.33.33.33"

  config.vm.forward_port "http", 80, 8080
end
